# Generated by Django 4.0 on 2021-12-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('category_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.FloatField()),
                ('product_brand', models.CharField(max_length=100)),
                ('screen_size', models.CharField(max_length=100)),
                ('cpu', models.CharField(default='Intel', max_length=100)),
                ('operating_system', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=1000)),
                ('image', models.ImageField(default='computer_and_accessories_images/default.png', upload_to='images_computer/')),
            ],
            options={
                'db_table': 'Computer',
            },
        ),
    ]
