# Generated by Django 4.0 on 2021-12-08 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('category', '0001_initial'),
        ('computer', '0002_remove_computer_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='category_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
        migrations.AddField(
            model_name='computer',
            name='department_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='department.department'),
        ),
    ]
